services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://list_extraction:97cPxe78jaKQ5YC6@34.27.81.23:5432/list_extraction
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=list_extraction
      - POSTGRES_PASSWORD=97cPxe78jaKQ5YC6
      - POSTGRES_DB=list_extraction

volumes:
  postgres_data: